In [15]:
import sqlite3

# Add a timeout to handle locking issues
conn = sqlite3.connect('trackdb.sqlite', timeout=50)
cur = conn.cursor()

# Make some fresh tables using executescript()
cur.executescript('''
            DROP TABLE IF EXISTS Artist;
            DROP TABLE IF EXISTS Album;
            DROP TABLE IF EXISTS Track;
            DROP TABLE IF EXISTS Genre;

            CREATE TABLE Artist (
                id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
                name    TEXT UNIQUE
            );

            CREATE TABLE Album (
                id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
                artist_id INTERGET,
                title   TEXT UNIQUE
            );
            
             CREATE TABLE Genre (
                id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
                name   TEXT UNIQUE
                
            );

            CREATE TABLE Track (
                id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
                title TEXT  UNIQUE,
                artist_id INTERGET,
                genre_id INTEGER,
                album_id  INTEGER,
                len INTEGER, rating INTEGER, count INTEGER
            );
            ''')

# Prompt the user for the file name
ftracks = input('Enter file name: ') #use [tracks.csv] 
if len(ftracks) < 1:
    ftracks = 'tracks.csv'

# Try opening the file with error handling
try:
    ftracks = open(ftracks,  encoding='ISO-8859-1')
except FileNotFoundError:
    print(f"Error: File '{ftracks}' not found.")
    exit()

# Process each line from the file
for line in ftracks:
    line = line.strip()
    pieces = line.split(',')
    if len(pieces) < 6: 
        continue

    name = pieces[0]
    artist = pieces[1]
    album = pieces[2]
    count = pieces[3]
    rating = pieces[4]
    length = pieces[5]
    genre = pieces[6] if len(pieces) > 6 else None  # Handle missing genre

    # print(name, artist, album, count, rating, length, genre)

    # Insert or ignore Artist
    cur.execute('''INSERT OR IGNORE INTO Artist (name) 
        VALUES ( ? )''', (artist,))
    cur.execute('SELECT id FROM Artist WHERE name = ? ', (artist,))
    artist_id = cur.fetchone()[0]

    # Insert or ignore Album
    cur.execute('''INSERT OR IGNORE INTO Album (title, artist_id) 
        VALUES ( ?, ? )''', (album, artist_id))
    
    cur.execute('SELECT id FROM Album WHERE title = ? ', (album,))
    album_id = cur.fetchone()[0]
    
    #insert or ignore Genre
    cur.execute('''INSERT OR IGNORE INTO Genre (name) 
        VALUES ( ? )''', (genre,))
    cur.execute('SELECT id FROM Genre WHERE name = ? ', (genre,))
    genre_id = cur.fetchone()[0]
    
    # #conditional check if genre exist
    # if row is None:
    #     # Insert the genre if it doesn't exist
    #     cur.execute('''INSERT INTO Genre (title) VALUES (?)''', (genre,))
    #     conn.commit()  # Commit the new genre
    #     # Fetch the newly inserted genre
    #     cur.execute('SELECT id FROM Genre WHERE title = ? ', (genre,))
    #     genre_id = cur.fetchone()[0]
    # else:
    #     genre_id = row[0]

    # Insert or replace Track
    # cur.execute('''INSERT OR REPLACE INTO Track
    #     (title, album_id, len, rating, count, genre_id, artist_id) 
    #     VALUES ( ?, ?, ?, ?, ?, ?, ? )''', 
    #     (name, album_id, length, rating, count, genre_id, artist_id))
    
    cur.execute(
        '''INSERT OR REPLACE INTO Track
        (title, name, album, genre) 
        VALUES ( ?, ?, ?, ? )''', 
        (name, artist, album, genre)
    )
    
    # Commit the changes once, after all rows have been processed
conn.commit()

# Close the database connection after the script finishes
conn.close()

Enter file name:  tracks.csv

OperationalError: table Track has no column named artist